# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.chrome.options import Options
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
import unittest

class TestUkraine(unittest.TestCase):
  def setUp(self):
    chrome_options = Options()
    chrome_options.add_argument("--headless")
    self.driver = webdriver.Chrome(chrome_options=chrome_options)
    self.vars = {}
  
  def tearDown(self):
    self.driver.quit()
  
  def test_ukraine(self):
    # Test name: Ukraine
    # Step # | name | target | value
    # 1 | open | https://covid19.gov.ua/en/ | 
    self.driver.get("https://covid19.gov.ua/en/")
    # 2 | waitForElementVisible | css=.one-field:nth-child(6) > .field-value | 30000
    WebDriverWait(self.driver, 30000).until(expected_conditions.visibility_of_element_located((By.CSS_SELECTOR, ".one-field:nth-child(6) > .field-value")))
    # 3 | storeText | css=.one-field:nth-child(6) > .field-value | tests
    self.vars["tests"] = self.driver.find_element(By.CSS_SELECTOR, ".one-field:nth-child(6) > .field-value").text
    # 4 | close |  | 
    self.driver.close()
  
